# Generated by Django 2.1 on 2018-08-21 01:26

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=30)),
                ('nome_fantasia', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='Número do cnpj')),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Número de telefone')),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('categoria', models.PositiveIntegerField(choices=[(1, 'Supermercado'), (2, 'Restaurante'), (3, 'Borracharia'), (4, 'Oficina'), (5, 'Posto')], verbose_name='Tipo de estabelecimento')),
                ('status', models.BooleanField(default=False, verbose_name='Ativo ou Inativo')),
                ('Agencia bancaria', models.CharField(max_length=5)),
                ('Conta bancaria', models.CharField(max_length=8)),
            ],
        ),
    ]
